require.config({
    //baseUrl:the same directory of main.js
    paths: {    	
        //Library
        "jquery": "../js/jquery",
        "moment": "../js/moment",
        "angular": "../js/angular",
        "angularAMD": "../js/angularAMD",
        "angular-route": "../js/angular-route",
        "angular-resource": "../js/angular-resource",
        "bootstrap": "../js/bootstrap",
        "bootstrap-datepicker": "../js/bootstrap-datepicker",
        "bootstrap-datetimepicker": "../js/bootstrap-datetimepicker",
        "bootstrap-paginator": "../js/bootstrap-paginator",
        "jquery.form": "../js/jquery.form",
        "jquery.hotkeys": "../js/jquery.hotkeys",
        "jquery.tablesorter": "../js/jquery.tablesorter",
        "jquery.validate": "../js/jquery.validate",
        "jquery.flot": "../js/jquery.flot",
        "jquery.flot.categories": "../js/jquery.flot.categories",
        "jquery.flot.resize": "../js/jquery.flot.resize",
        "jquery.flot.time": "../js/jquery.flot.time",
        "jquery.flot.pie": "../js/jquery.flot.pie",
        "select2": "../js/select2",
        "iCheck": "../js/iCheck",
        "bootstrap-wysiwyg": "../js/bootstrap-wysiwyg",
        "bootstrap-editable":"../js/bootstrap-editable",
        "ng-infinite-scroll":"../ng-infinite-scroll.min.js",
        "ui-bootstrap":"../ui-bootstrap-tpls-0.13.0.min.js",
        //Customize
        "ui.select2":"common/angular-ui/select2",
        "validateConfig": "common/util/validateConfig",
        //Controller
        "flotCtrl":"flot/flot",
        "pieCtrl":"pie/pie",
        "userCtrl":"user/user",
        "scrollCtrl":"scroll/scroll",
    },
    shim: {
        "angular": ["jquery"],
        "angularAMD": ["angular"],
        "angular-route": ["angular"],
        "angular-resource": ["angular"],
        "bootstrap": ["jquery"],
        "bootstrap-datepicker": ["bootstrap", "moment"],
        "bootstrap-datetimepicker": ["bootstrap", "moment"],
        "bootstrap-paginator": ["bootstrap"],  
        "bootstrap-wysiwyg": ["bootstrap"],
        "bootstrap-editable": ["bootstrap"],
        "jquery.tablesorter": ["jquery"],
        "jquery.validate": ["jquery"],
        "jquery.hotkeys":["jquery"],
        "jquery.flot":["jquery"],
        "jquery.flot.pie":["jquery.flot"],
        "jquery.flot.categories":["jquery.flot"],
        "jquery.flot.resize":["jquery.flot"],
        "jquery.flot.time":["jquery.flot"],
        "select2": ["jquery"],
        "ui.select2":["select2"],
        "iCheck": ["jquery"],
        "ng-infinite-scroll":["angular"],
        "ui-bootstrap":["bootstrap", "angular"]
    },
    deps:["app"]
});