// Generated by CoffeeScript 1.7.1
define(["app",
        "jquery.flot",
        "jquery.flot.pie"],function(app){
    app.register.directive("pie",function(){
        var tooltipId = "tooltip-pie-" + new Date().getTime();
        return {
            restrict: 'EA',
            template: '<div></div>',
            scope: {
                dataset: '=',
                options: '=',
                eoptions: "=",
                callback: '='
            },
            link: function(scope, element, attributes) {
                var height, init, onDatasetChanged, onOptionsChanged, plot, plotArea, width, tooltip;
                plot = null;
                width = attributes.width || '100%';
                height = attributes.height || '100%';
                if (!scope.dataset) {
                    scope.dataset = [];
                }
                if (!scope.options) {
                    scope.options = {
                        legend: {
                            show: false
                        }
                    };
                }
                plotArea = $(element.children()[0]);
                plotArea.css({
                    width: width,
                    height: height
                });
                init = function() {
                    var plotObj;
                    plotObj = $.plot(plotArea, scope.dataset, scope.options);
                    if (scope.callback) {
                        scope.callback(plotObj);
                    }
                    return plotObj;
                };
                onDatasetChanged = function(dataset) {
                    if (plot) {
                        plot.setData(dataset);
                        plot.setupGrid();
                        return plot.draw();
                    } else {
                        return plot = init();
                    }
                };
                onOptionsChanged = function() {
                  return plot = init();
                };
                scope.$watchCollection('dataset', onDatasetChanged, true);
                scope.$watch('options', onOptionsChanged, true);
                tooltip = $("#" + tooltipId);
                tooltip.length || ( tooltip = $("<div class='flot-tooltip text-nowrap bg-info'></div>").attr("id", tooltipId).appendTo("body"));
                element.bind("plothover", function (event, pos, item) {
                  if (item) {
                    var text = scope.eoptions && scope.eoptions.getPointHoverData
                      ? scope.eoptions.getPointHoverData(event, pos, item) : item.series.label + ": " + item.series.data[0][1];
                    var offset = 10,
                        top = 0, 
                        left = 0, 
                        windowWidth = $('body').width(),
                        windowHeight = $('body').height(),
                        tooltipWidth = tooltip.outerWidth(true) + offset,
                        tooltipHeight = tooltip.outerHeight(true) + offset;
                    pos.pageX + tooltipWidth > windowWidth ? (left = pos.pageX - tooltipWidth) : (left = pos.pageX + offset);
                    pos.pageY + tooltipHeight > windowHeight ? (top = pos.pageY - tooltipHeight) : (top = pos.pageY + offset);
                    tooltip.html(text).css({top: top, left: left}).fadeIn(200);
                  } else {
                    tooltip.hide();
                  }
                });
                return scope;
            }
        };
    });
})